.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TASKCOACH 1 "December 25, 2008"
.SH NAME
taskcoach \- A friendly and simple task manager
.SH SYNOPSIS
.B taskcoach
.RI [ options ]
.br
.SH DESCRIPTION
.PP
\fBtaskcoach\fP Task Coach is a simple open source todo manager to manage personal tasks
and todo lists. It grew out of a frustration that well-known task managers,
such as those provided with Outlook or Lotus Notes, do not provide
facilities for composite tasks
.SH OPTIONS
The application follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-i INIFILE, \-\-ini=INIFILE
use the specified INIFILE for storing settings
.TP
.B \-l LANGUAGE, \-\-language=LANGUAGE
use the specified LANGUAGE for the GUI (e.g. "nl" or "fr")
.TP
.B \-p POFILE, \-\-po=POFILE
use the specified POFILE for translation of the GUI
.SH SEE ALSO
Official web page: www.taskcoach.org
.SH AUTHOR
taskcoach was written by Frank Niessink and Jerome Laheurte <developers@taskcoach.org>.
.PP
This manual page was written by Alejandro Garrido Mota <garridomota@gmail.com>,
for the Debian project (and may be used by others).
